### ISSUE TITLE
MemoryLeakFix  0.3.4 MC 1.18.2 crash when open world

### ISSUE THREAD

**Issue by crest1993** [fxmorin/memoryLeakFix#10]
[crash-2022-06-03_15.14.09-client.txt](https://github.com/fxmorin/memoryLeakFix/files/8830842/crash-2022-06-03_15.14.09-client.txt)

**Comment by sisby-folk** [comment]
Seconded.

**Comment by FxMorin** [comment]
I'll look into it

**Comment by FxMorin** [comment]
This will be fixed in v0.3.5
