### ISSUE TITLE
Crash on startup 1.19.4 with beta 6

### ISSUE THREAD

**Issue by voidrinix** [fxmorin/memoryLeakFix#101]
Crash log: https://mclo.gs/45tqeYw

**Comment by contariaa** [comment]
this is an issue with Litematica Printer, memoryleakfix just fixes a memoryleak where mixin uses up a bunch of ram for storing mixins by forceloading them and clearing that cache, during that forceloading one of Litematica Printer's mixins seems to have errored

**Comment by FxMorin** [comment]
Updating fabric loader to the latest version fixes this issue
