### ISSUE TITLE
Guess the pic really sums it up

### ISSUE THREAD

**Issue by Minebrah** [fxmorin/memoryLeakFix#102]
![Screenshot (7)](https://user-images.githubusercontent.com/128096529/228053373-13f8eec1-7e99-4802-8bcd-26d3cc98ae2a.png)

**Comment by contariaa** [comment]
dont use the sources jar

**Comment by contariaa** [comment]
oh @fxmorin it seems your new publishing script uploads the sources and the dev jar instead of the normal one

**Comment by contariaa** [comment]
seems this is only an issue on curseforge

**Comment by contariaa** [comment]
nevermind im stupid its right there, so yea this is the solution:

> dont use the sources jar
