### ISSUE TITLE
[Question] About teamperature cache

### ISSUE THREAD

**Issue by Kasualix** [fxmorin/memoryLeakFix#106]
Isn't it removed by Lithium?

https://github.com/CaffeineMC/lithium-fabric/commit/4553ccb0a02049c588fbacd689afbace067add82

**Comment by FxMorin** [comment]
Yes ive talked with 2No about how I believe that the cache is useful in some situations, if implemented properly like it is in this mod.
Honestly as long as its either MemoryLeakFix or Lithium, the problem is solved
