### ISSUE TITLE
Crash with Extra Alchemy's mixins

### ISSUE THREAD

**Issue by Sunconure11** [fxmorin/memoryLeakFix#112]
https://gist.github.com/Sunconure11/6cd756098280036fd20f8d7849b3d409

**Comment by Sunconure11** [comment]
Immersive portals and polymer are also being blamed.

**Comment by Sunconure11** [comment]
@zabi94

I realize you are a bit... busy, but maybe you can shed light here?

**Comment by zabi94** [comment]
Does removing extra alchemy fix the issue?

**Comment by Sunconure11** [comment]
I can check.

**Comment by Sunconure11** [comment]
Yes, it does.

**Comment by FxMorin** [comment]
Ya sorry don't have the time to look into this at the moment. Have you tried updating to the last est fabric loader version?

**Comment by Sunconure11** [comment]
I'm on Quilt

**Comment by Sunconure11** [comment]
Do you need me to give some more details?

**Comment by FxMorin** [comment]
Please report this to extra alchemy's, there is nothing else I can do about it

**Comment by Sunconure11** [comment]
![BC1F85B4-C74B-40C3-9B64-A12C7E27284F](https://github.com/fxmorin/MemoryLeakFix/assets/5614902/2def429e-2cfa-42c7-b222-d22f7fc8ece7)

**Comment by FxMorin** [comment]
Sadly its not worth fixing it on my end either.
