### ISSUE TITLE
Crash with FastLoad

### ISSUE THREAD

**Issue by Ahptt** [fxmorin/memoryLeakFix#113]
Per the [FastLoad issue #86](https://github.com/BumbleSoftware/Fastload/issues/86), there is a crash when attempting to run both MemoryLeakFix and Fastload. I am placing this here to be reviewed. Thanks.

**Comment by ClaudiusMinimus** [comment]
My server crashes on start-up as well with memoryleakfix and Fast Load 3.3.8
Removed memoryleakfix and runs smoothly
[Crash Report](https://www.pastbin.net/memoryleakfix-fabric-crash)

**Comment by sternschnaube** [comment]
The problem got resolved. This can be closed.
