### ISSUE TITLE
Fails to Launch with Saturn (Forge 1.18.2 latest)

### ISSUE THREAD

**Issue by Atlantispy** [fxmorin/memoryLeakFix#115]
Saturn updated and now seems to be trying to modify the same thing, causing the game to not launch. 

Have reported it to them too.

https://github.com/AbdElAziz333/Saturn/issues/9

**Comment by FxMorin** [comment]
After looking at the code. MemoryLeakFix does everything Saturn does and more. So there is no reason to use Saturn
