### ISSUE TITLE
Game crashes on startup.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [fxmorin/memoryLeakFix#118]
Minecraft version: 
1.18.2

Forge version: 
40.2.2

Mod version: 
1.0.0

Logs:
[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/11455630/latest.log)
[debug.log](https://github.com/fxmorin/MemoryLeakFix/files/11455631/debug.log)

**Comment by contariaa** [comment]
this is the same crash as https://github.com/fxmorin/MemoryLeakFix/issues/115, so im gonna close this issue

**Comment by contariaa** [comment]
actually i cant lol, @fxmorin would you do the honors?
