### ISSUE TITLE
[Crash] MemoryLeakFix crashes on 1.20 with sodium

### ISSUE THREAD

**Issue by TH3N3WN00B** [fxmorin/memoryLeakFix#123]
As title says..

Crash log: https://paste.gg/p/anonymous/da7348f7d6c3450c901994caf44f4e23

Mod list (without MemoryLeakFix):
![image](https://github.com/fxmorin/MemoryLeakFix/assets/10799738/561f3296-132f-4486-8aaf-4949c91b4a6f)

**Comment by HhiPyrene** [comment]
Can also confirm.
[crash-2023-06-09_24.07.36.6100-quilt_loader.txt](https://github.com/fxmorin/MemoryLeakFix/files/11690821/crash-2023-06-09_24.07.36.6100-quilt_loader.txt)
I changed the loader version dependence to 0.14.19, so that it can work with Quilt.

**Comment by Aertic** [comment]
same here, I'm on Quilt 1.20 and it says it needs a newer fabric version

**Comment by FxMorin** [comment]
Fixed in [v1.1.1](https://github.com/fxmorin/MemoryLeakFix/releases/tag/v1.1.1)
