### ISSUE TITLE
[Crash] [Fabric 1.19.2] Version 1.1.0 not running at all

### ISSUE THREAD

**Issue by xR4YM0ND** [fxmorin/memoryLeakFix#124]
## Walkthrough
I tried the 1.1.0 with our modpack, crashed cause of ARRP.

I disabled ARRP & all mods that need that, still crashed cause of Debugify.

I tried it standalone, still crashed.
`Uncaught exception in thread "main"`

## Logs
[Modpack latest.log with ARRP](https://gist.github.com/xR4YM0ND/af4261a89409ac9bb28092f1b277c0c6)
[Modpack latest.log without ARRP](https://gist.github.com/xR4YM0ND/f22511fa57aecd7bb68739969d67df5e)

[Standalone latest.log](https://gist.github.com/xR4YM0ND/64453b1cf51cdad1b7656ed913d22559)

**Comment by RomanPro100** [comment]
Same issue, but on 1.19.4. Also crashes with Chat Patches, Debugify, ImmediatelyFast or Sodium.
Logs:
[Just MemoryLeakFix](https://github.com/fxmorin/MemoryLeakFix/files/11712050/tl-logger16975985758431571872.txt)
[With Chat Patches](https://github.com/fxmorin/MemoryLeakFix/files/11712059/tl-logger13112741298420731724.txt)

**Comment by FxMorin** [comment]
Fixed in [v1.1.1](https://github.com/fxmorin/MemoryLeakFix/releases/tag/v1.1.1)
