### ISSUE TITLE
Mob AI completely stops

### ISSUE THREAD

**Issue by xhoneybear** [fxmorin/memoryLeakFix#129]
Minecraft version: 1.20
After loading a world mobs just do nothing. Their AI is completely non-functional. No movement and no animations.
My game has other mods installed so it might be a compatibility issue. I'll try to troubleshoot it

**Comment by FxMorin** [comment]
Without logs, theres not much I can do

**Comment by xhoneybear** [comment]
Sorry, I had little time last week, I'll try to provide logs as soon as I can - tomorrow I hope. I'll also try to see if it's anything related to mod compatibility. Really sorry for taking a long time with it

**Comment by xhoneybear** [comment]
It seems that this issue might not be related to the mod. It just happened again without the mod enabled and got resolved after enabling it. Just sort of random issues on my hardware maybe :| Closing. since it's probably not relevant.

**Comment by xhoneybear** [comment]
It seems that this issue might not be related to the mod. It just happened again without the mod enabled and got resolved after enabling it. Just sort of random issues on my hardware maybe :| Closing. since it's probably not relevant. Sorry for the trouble! ^^'

**Comment by xhoneybear** [comment]
Just upgraded MC to 1.20.1 and Immersive Portals noted an incompatibility with Entity Culling, removing the latter does seem to actually help. I don't know why removing MLF seemed to help before but as odd as it seems it was most likely purely coincidental. Once again sorry for a false alert!
