### ISSUE TITLE
isn't there a 1.12.2 version?

### ISSUE THREAD

**Issue by Zane2b2t** [fxmorin/memoryLeakFix#133]
on my old pc i used to have a 1.12 version but i can't find it anywhere on the web
this mod is supposed to be for modpacks anyways why is there no 1.12 anymore

**Comment by FxMorin** [comment]
There was never a 1.12.2 version. The mod only supports 1.14.4+

**Comment by Zane2b2t** [comment]
> 

could've been a diffrent mod with the same name. thanks

**Comment by FxMorin** [comment]
> could've been a diffrent mod with the same name. thanks

Better not be...
