### ISSUE TITLE
Compatibility with ViaFabric+?

### ISSUE THREAD

**Issue by RealmKebab** [fxmorin/memoryLeakFix#134]
Any thoughts for compatibility with ViaFabric+?
(ignore tps-hud, i removed it from my modlist)
It crashes because of incompatibility (shown in this log):

https://mclo.gs/nIl1TqD

**Comment by RealmKebab** [comment]
(how much edits is too much)

**Comment by FxMorin** [comment]
Use the latest version

**Comment by RealmKebab** [comment]
> Use the latest version

i am

**Comment by RealmKebab** [comment]
i am

**Comment by FxMorin** [comment]
The latest version of ViaFabric+

**Comment by RealmKebab** [comment]
ok thanks lol
