### ISSUE TITLE
[forge] absent 1.20.1 inclusion

### ISSUE THREAD

**Issue by ColonelGerdauf** [fxmorin/memoryLeakFix#136]
The mod is supposed to be compatible in 1.20.1, but is only listed up to 1.20 in Forge, both in Curseforge and Modrinth.

This can create awkwardness when it comes to updating via launchers.

**Comment by ScadeBlock** [comment]
Yes , 1.20.1 only changes few things. So maybe many 1.20 mods work on 1.20.1. And i think MemoryLeakFix is one of them. If you want to try, just open forge memoryleakfix 1.17+ mod with any archive software ,then go to pack.mcmeta and changes `pack_format` from 7 to 15 (I tested it and well it works, but i amn't  sure that works properly fine and stable)

**Comment by ColonelGerdauf** [comment]
That may be true, but that does not resolve the issue of awkwardness of systems that attempt to do automated updates. There will be constant whining about the strict version mismatch.

**Comment by FxMorin** [comment]
I hate forge. Always wants to make my job harder

**Comment by GabbyDG2805** [comment]
I would also appreciate an official forge 1.20.1 version :)

**Comment by FxMorin** [comment]
The problem here is that the pack_format gets used for all versions, not just 1.20.1
I'm not completely sure how to do that without making separate builds. Not sure why forge would break like that either

**Comment by Linguardium** [comment]
It sounds like its only missing the flag/checkbox on CF and modrinth files indicating that the mod supports 1.20.1 so that the launchers using the project metadata can "see" them

**Comment by ColonelGerdauf** [comment]
> The problem here is that the pack_format gets used for all versions, not just 1.20.1 I'm not completely sure how to do that without making separate builds. Not sure why forge would break like that either

This isn't about Forge in isolation. The thing is, launchers are quite strict (for good reasons) about version match listed on the linked platform (CF or Modrinth) before doing a mod update. If a launcher like Prism detects a mod not ID'ed on the correct version from the platform, it complains about the version mismatch and refuses to update until there is a version with the right support from the platform.

The matter of fact is, you have not marked 1.20.1 on the Forge release, with v1.1.1.

**Comment by ColonelGerdauf** [comment]
It appears to be resolved with v1.1.2, but do not forget about version support on Modrinth and CF next time.

**Comment by ColonelGerdauf** [comment]
This is to highlight very clearly what I mean.
![image](https://github.com/fxmorin/MemoryLeakFix/assets/6895655/891d2b6f-8a58-480d-ad33-1fd06801713d)

That is not good, and look at these in comparison
![image](https://github.com/fxmorin/MemoryLeakFix/assets/6895655/7d3cdd17-f0f2-48a1-aba9-79cdb15322ba)
![image](https://github.com/fxmorin/MemoryLeakFix/assets/6895655/fdb978f3-cf16-44ea-9a0e-2f8db55db374)
