### ISSUE TITLE
Memory keep leaking even with latest version installed

### ISSUE THREAD

**Issue by goodair220917** [fxmorin/memoryLeakFix#141]
As issue title said, even keep leaking memory with Java -Xmx argument included.

Temporary solution I'm using:

prlimit --pid [Minecraft's PID]  --as=40960000000

Here's my mod list:

Mods:
  [✔] 3dskinlayers-fabric-1.5.4-mc1.20.1
  [✔] advanced-xray-fabric-1.20.1-1.6.0-build.17
  [✔] advancementinfo-1.20-fabric0.83.0-1.4
  [✔] AdvancementPlaques-1.20.1-fabric-1.4.11
  [✔] animatica-0.6+1.20
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] architectury-9.1.12-fabric
  [✔] armorskin-0.2
  [✔] autoreconnect-2.2.1
  [✔] axolotl-item-fix-1.1.7
  [✔] badpackets-fabric-0.4.1
  [✔] betterconfig-1.1.5
  [✔] betterstats-2.10.3+1.20.1
  [✔] bobby-5.0.1
  [✔] CITResewn-1.1.3+1.20
  [✔] clickthrough-1.20-fabric0.83.0-0.4.1
  [✔] clientcommands-2.8.3
  [✔] cloth-config-11.1.106-fabric
  [✔] continuity-3.0.0-beta.3+1.20.1
  [✔] Craftify-1.20.1-1.11.0-fabric
  [✔] custom_hud-3.1.2+1.20.1
  [✔] dashloader-5.0.0-beta.2+1.20.0
  [✔] EquipmentCompare-1.20.1-fabric-1.3.7
  [✔] Essential Dependencies
  [✔] Essential-fabric_1-19
  [✔] exordium-fabric-1.1.3.1-mc1.20.1
  [✔] fabric-api-0.86.1+1.20.1
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] firstperson-fabric-2.2.3-mc1.20
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] fpsdisplay-3.1.0+1.20.x
  [✔] freecam-fabric-modrinth-1.2.1+1.20
  [✔] fscript-3.2.1
  [✔] holdthatchunk-2.0.1+1.19
  [✔] Iceberg-1.20.1-fabric-1.1.14
  [✔] indium-1.0.25+mc1.20.1
  [✔] InventoryProfilesNext-fabric-1.20-1.10.6
  [✔] iris-mc1.20.1-1.6.8
  [✔] language-reload-1.5.8+1.20.1
  [✔] lazydfu-0.1.3
  [✔] LegendaryTooltips-1.20.1-fabric-1.4.4
  [✔] libIPN-fabric-1.20-3.0.2
  [✔] libjf-3.12.2
  [✔] litematica-fabric-1.20.1-0.15.3
  [✔] litematica-printer-1.20.1-3.2.1
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] malilib-fabric-1.20.1-0.16.1
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] modmenu-7.2.1
  [✔] morechathistory-1.19.1-1.1.1
  [✔] Neat-1.20-35-FABRIC
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] open-parties-and-claims-fabric-1.20.1-0.19.3
  [✔] optigui-2.1.5
  [✔] Prism-1.20.1-fabric-1.0.5
  [✔] README
  [✔] replaymod-1.20.1-2.6.13
  [✔] respackopts-4.4.0
  [✔] RoughlyEnoughItems-12.0.634
  [✔] Rrls-1.20.1-3.1.1-fabric (1)
  [✔] short-grass-1.2.0
  [✔] shulkerboxtooltip-fabric-4.0.4+1.20.1
  [✔] sodium-fabric-mc1.20.1-0.5.2
  [✔] soundphysics-fabric-1.20.1-1.1.2
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] stendhal-1.3.9-1.20
  [✔] survivalflight-1.3.3
  [✔] viafabric-0.4.10+40-main
  [✔] worldedit-mod-7.2.15
  [✔] wthit-fabric-8.3.0
  [✔] Xaeros_Minimap_23.6.1_Fabric_1.20
  [✔] XaerosWorldMap_1.32.0_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.1.0+1.20
  [✔] yosbr-0.1.2
  [✔] Zoomify-2.11.0
  
  Further information of my platform:
  Java is version 17.0.8, using 64 (amd64) architecture, from Private Build.
  Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
  NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] (rev a1)

Tell me if logs of game also required.

**Comment by fxmorin** [comment]
Should be fixed in v1.1.2

**Comment by FxMorin** [comment]
How can you tell?
Also I don't fix memory leaks in other mods
