### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by MoreCaveSounds** [fxmorin/memoryLeakFix#144]
Crashes with immediatelyfast

**Comment by FxMorin** [comment]
Should be fixed in v1.1.2

**Comment by Poopooracoocoo** [comment]
**Edit: Resolved** 
Thank you so much! I noticed that the Modrinth versions aren't marked as being for the full range of Minecraft versions that it supports. Thought I'd let you know in case you weren't already aware.
