### ISSUE TITLE
Hello, I'm asking you to make fabric or quilt for version 1.20.2 on modrinth, thank you very much!

### ISSUE THREAD

**Issue by verixyt3** [fxmorin/memoryLeakFix#149]
Hello, I'm asking you to make fabric or quilt for version 1.20.2 on modrinth, thank you very much!

**Comment by AstroAbyss** [comment]
I need it as a 1.20.2 update as well!

**Comment by ajaxnotmeta** [comment]
me 3, and possibly also 1.20.3 as well since i heard the relase of that one were around the corner

**Comment by Margen67** [comment]
#153
