### ISSUE TITLE
Seems not compatible with Sodium

### ISSUE THREAD

**Issue by IceeAlin** [fxmorin/memoryLeakFix#15]
As title.

**Comment by FxMorin** [comment]
Are you using v0.1.4 and how do you know?
I tested it myself to make sure it does

**Comment by IceeAlin** [comment]
I'm terribly sorry, I've made a stupid mistake. Instead of downloading the mod from Modrinth, I downloaded the mod from the launcher's download function. This caused me not to get the right mod file and I couldn't launch the game. I am very sorry that I have brought you unnecessary trouble by asking questions without doing more checks.

**Comment by FxMorin** [comment]
lol all good
