### ISSUE TITLE
Crashing when loading world using Fabric 1.20.2

### ISSUE THREAD

**Issue by spikeymikey0196** [fxmorin/memoryLeakFix#150]
I've recently just updated everything to Fabric 1.20.2 as it all worked fine with Fabric 1.20.1 but for some reason it crashes everytime i load a world when the memoryleakfix-fabric-1.17+-1.1.2.jar is activated. I'm unsure as to why it's happening but it's only an issue for 1.20.2.
I've saved the crash report and attached it below.
[crash-2023-10-26_01.20.15-client.txt](https://github.com/FxMorin/MemoryLeakFix/files/13171719/crash-2023-10-26_01.20.15-client.txt)

**Comment by thatoneiuse** [comment]
Same issue. If I remove MemoryLeakFix the game loads just fine.
[crash-2023-10-25_23.25.15-client.txt](https://github.com/FxMorin/MemoryLeakFix/files/13172657/crash-2023-10-25_23.25.15-client.txt)

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
