### ISSUE TITLE
[1.18.2] Crash on Startup

### ISSUE THREAD

**Issue by Waterspark63** [fxmorin/memoryLeakFix#152]
When I have MemoryLeakFix and TISAdvanced in the same launch, it crashes immediately with a mixin failure with hugescreenshots.
Forge: 1.18.2-40.2.11
MLF: 1.17+ 1.1.2
TIS-3D: 1.18.2-1.6.8-2ac5c5f (No Crash)
TISAdvanced: 1.18.2-0.3.0 (No Crash), -> 1.18.2-0.3.1 (Crashes)
[latest.log](https://github.com/FxMorin/MemoryLeakFix/files/13260867/latest.log)

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
