### ISSUE TITLE
Newest update breaks connection to server

### ISSUE THREAD

**Issue by 2el222** [fxmorin/memoryLeakFix#158]
MemoryLeakFix 1.1.3 breaks connection to online servers, both server and client start up and everything seems fine, but server just shows "pinging..." and u cant connect no matter how much u wait. Downgrading back to 1.1.2 fixes the issue

**Comment by 50t0r25** [comment]
same issue here, minecraft 1.20.1, fabric 0.15.3, mod is only on client and can't connect to any server.

Edit: noticed that the file size of the fabric,1.17+ version is suspiciously small compared to the others and the previous updates... Could be a build issue?

**Comment by Jasraj11** [comment]
Same here 1.20.1 also

**Comment by Jasraj11** [comment]
its version 1.1.3 From the mod 1.1.2 works perfect

**Comment by dopemike** [comment]
Same here!

**Comment by FxMorin** [comment]
Please try with: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.4

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
