### ISSUE TITLE
Crashing on startup on 1.19.2 Quilt

### ISSUE THREAD

**Issue by Sunconure11** [fxmorin/memoryLeakFix#159]
https://pastebin.com/99AR0nir

**Comment by FxMorin** [comment]
Please try with: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.4

**Comment by Sunconure11** [comment]
Will test shortly, helping debug an unrelated mod right now

**Comment by Sunconure11** [comment]
https://pastebin.com/s1JXi6Vk

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
