### ISSUE TITLE
Crash on startup with BYG/Terrablender active [1.19]

### ISSUE THREAD

**Issue by aisukuma** [fxmorin/memoryLeakFix#16]
I get a mixin error with just this mod and Oh the Biomes You'll Go/Terrablender and my Minecraft instance crashes on startup. Corgi is also aware of the crash as I have just reported it to him on the Discord server.

Here is the [gist link of the latest.log](https://gist.github.com/aisukuma/5603f967018bc0d8902104537092d1ce). 

Edit: This is for Minecraft 1.19

**Comment by FxMorin** [comment]
Yes, this has to be fixed from their side. This is probably due to a mixin that has an incorrect remap option or gets loaded when it shouldn't have been

**Comment by CorgiTaco** [comment]
@fxmorin this method in question works entirely fine on my side in BYG 1.19: https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/java/potionstudios/byg/mixin/access/WorldGenRegistryDumpReportAccess.java#L13-L17

**Comment by FxMorin** [comment]
@CorgiTaco Yes although MemoryLeakFix may load some mixins that would usually not be loaded due to never being loaded/other reasons.
I have not looked into why BYG crashes tho, although its not a conflict so it will need to be fixed from BYG's side

**Comment by greensad** [comment]
This is has some circular irony to it, BYG causes the chunk border lag to worsen, Debugify/Forget Me Chunk fixes that issue but causes memory leaks, Memory Leak Fix fixes the Debugify/Forget Me Chunk leaks but is incompatible with BYG.

Unfortunately IDK if CorgiTaco has seen your reply @fxmorin but I'll repost the issue over there.
