### ISSUE TITLE
1.1.3 interferes with ability to connect to servers

### ISSUE THREAD

**Issue by LessThanBenji** [fxmorin/memoryLeakFix#161]
Hi, just thought I'd quickly point this out for you -- I'm playing on 1.19.4, I noticed 1.1.3 was out today and updated from 1.1.2, and immediately found I couldn't connect to any servers in the Multiplayer menu. They all sat on "Pinging..." and when I went to join, I got the "Connecting to server..." screen for 30 seconds until it changed to "Timed out". Rolling back to 1.1.2 immediately fixed this issue.

If you need any further details about my modded environment, my logs, or if you'd like to know anything else, just ask.

Cheers :)

**Comment by LessThanBenji** [comment]
Note: I believe this is related to #160, as I experienced that same issue as well. Again, rolling back to 1.1.2 fixed both.

**Comment by Poopooracoocoo** [comment]
#158

**Comment by sternschnaube** [comment]
I can't confirm this issue. Thanks to version 1.1.3 this mod is useable again on Fabric 1.20.2. Running it along 200 other popular mods and no connecting issues so far.

Please provide any helpful informations such as logs and your mod list @LessThanBenji.

**Comment by LessThanBenji** [comment]
[latest.log](https://github.com/FxMorin/MemoryLeakFix/files/13848297/latest.log)

Attached is a relevant log -- note, this is affecting 1.1.3 on 1.19.4, not 1.20.2. Mod-list is mentioned in there, and you'll see the exceptions memoryleakfix is throwing in there too.

Cheers, appreciate all your guys' work :))

**Comment by 909oce** [comment]
Confirmed on Fabric 1.20.1 running version 1.1.3. Rolling back to 1.1.2 fixed for me.

**Comment by FxMorin** [comment]
Please try with: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.4

**Comment by LessThanBenji** [comment]
[latest.log](https://github.com/FxMorin/MemoryLeakFix/files/13848954/latest.log)

Still not working, same issue as before. Attached a new log showing my attempt with 1.1.4 under all the same other conditions.

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
