### ISSUE TITLE
Crash on Startup with 1.1.3 on Quilt, Minecraft version 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [fxmorin/memoryLeakFix#162]
[crash-2024-01-06_00.47.48-client.txt](https://github.com/FxMorin/MemoryLeakFix/files/13848643/crash-2024-01-06_00.47.48-client.txt)

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
