### ISSUE TITLE
1.14 Breaks Connection To server [Again]

### ISSUE THREAD

**Issue by Jasraj11** [fxmorin/memoryLeakFix#165]
The newst Version [1.14] breaks The connection Like the Last time didnt Fix Anything 
while downgrading to 1.12 fix it

**Comment by FxMorin** [comment]
Pretty weird cause its working for me, so im not sure how to recreate it

**Comment by FudgeDumbo** [comment]
HI,
I have tested by removing optimization mods one by one and it does not work with krypton.
I do like how krypton works, so I also downgraded to 1.12 for now heh

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
