### ISSUE TITLE
(1.1.4 / 1.1.3) Crash on loading world with fabric 1.20.1 / Crash on startup with memoryleakfix + VMP fabric 1.20.1

### ISSUE THREAD

**Issue by neinwhal** [fxmorin/memoryLeakFix#166]
A partial continuation from https://github.com/RelativityMC/VMP-fabric/issues/57

When running fabric 1.20.1 with with appropriate latest APIs and only memory leak fix 1.1.4, using memory leak fix 1.1.4 will load the game, but crashes upon creation of a world / joining a world.
Crash logs: https://pastebin.com/raw/L81iRigw

Using it with VMP leads to an instant crash on startup. The logs for this can be retrieved in the issue linked above.

This is can be replicated for 1.1.3 as well.
1.1.2 is the only functional verison.

**Comment by FxMorin** [comment]
Fixed in: https://github.com/FxMorin/MemoryLeakFix/releases/tag/v1.1.5
