### ISSUE TITLE
[1.19.4 Fabric] Crashes on startup, unsure of actual reason

### ISSUE THREAD

**Issue by AbyssalVitality** [fxmorin/memoryLeakFix#167]
Every time I attempt to start Minecraft, the game crashes before entering the title screen. I have attempted this several times, and have deduced that MemoryLeakFix is the issue, as it crashes Minecraft, even with it being the only mod enabled.

Log file: https://mclo.gs/Mhocv13

Actual file: [latest.log](https://github.com/FxMorin/MemoryLeakFix/files/13856224/latest.log)

**Comment by FxMorin** [comment]
Please use the latest version. Which is v1.1.5
