### ISSUE TITLE
Reference map could not be read

### ISSUE THREAD

**Issue by Endrock6** [fxmorin/memoryLeakFix#168]
Version: 1.1.5 - 1.20.4
Loader: Fabric

I just updated to version 1.1.5 on my server and when launching it, I got this error. Since it's not a development environment I guess I'm not supposed to ignore the message but don't know what to do about it.
This is the error I received in my console:
"Reference map 'memoryleakfix-fabric-1.17+-fabric-refmap.json' for memoryleakfix-fabric.mixins.json could not be read. If this is a development environment you can ignore this message"

**Comment by FxMorin** [comment]
Does it crash? If not you can ignore that message.
It appears due to the fact that this mod does a couple workarounds to work on multiple versions and loaders all with the same code.

**Comment by Endrock6** [comment]
No, it doesn't crash it launches normally but take about 30 mins to do so. But I don't believe that is the fault of this mod.

**Comment by loplxl** [comment]
did you fix this?

**Comment by Endrock6** [comment]
Forgot to close this. Sorry.

**Comment by loplxl** [comment]
> Forgot to close this. Sorry.

i cant tell if that means you fixed it or you gave up lmfao, if you remember how you fixed it would u mind letting me know?
i dont really think this is a huge problem anyway since later in the log it says that memleakfix patched stuff so its not big

**Comment by Endrock6** [comment]
If you look at the explanation above you'll see that it's not a bug and isn't something that needs fixing. Unless of course it causes a crash which it hasn't for me and by the fact you mentioned you see later parts of the log it implies your game doesn't crash either.
