### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by mucookul** [fxmorin/memoryLeakFix#178]
Its that time again

**Comment by R00tB33rMan** [comment]
I successfully got this mod to work on 1.20.6 with virtually no issues. I'd give it a spin to confirm otherwise; however, I have yet to encounter any problems.

**Comment by RedCat888** [comment]
Did you just use the 1.20.4 version?

**Comment by wyrmiyu** [comment]
Sorry for necro-commenting, but in case the 1.20.4 version works for 1.20.6 etc., could you tag it accordingly on mod manager repos?

**Comment by FxMorin** [comment]
I wouldn't
