### ISSUE TITLE
Crash with MapAtlas

### ISSUE THREAD

**Issue by saintsareprey** [fxmorin/memoryLeakFix#18]
First of all sorry lol I created a blank one by accident

here's some info you might need and the crash log, the crash was on startup btw
fabric loader 0.14.7 - 1.18.2
fabric api 0.56.0
memoryleakfix 1.18.2 0.3.5

https://gist.github.com/AndyXTJ/c840a5ee3b53e066fea713b89d06e763

**Comment by FxMorin** [comment]
Can you please make an issue for MapAtlas, this is not a conflict so it needs to be fixed from there side

**Comment by saintsareprey** [comment]
I did, thanks for clarifying
