### ISSUE TITLE
Hydrogen has been discontinued 

### ISSUE THREAD

**Issue by espot07** [fxmorin/memoryLeakFix#2]
I saw you recommended the mod Hydrogen to be used with your mod in the README.md file and your Modrinth page, but that mod was discontinued by its creators. The mod [FerriteCore](https://github.com/malte0811/FerriteCore) offers much of the same functionality as Hydrogen but is still actively supported for the latest Minecraft versions. The mod was even recommended by the creators of Hydrogen. Just wanted to bring this to your attention!

![image](https://user-images.githubusercontent.com/91640297/170783607-3cc8eafa-e13f-4326-8506-41610394eb0d.png)

**Comment by fxmorin** [comment]
I personally have never profiled FerriteCore, although ill put it on my to-do list. I'll remove Hydrogen tho
