### ISSUE TITLE
1.19 Crashing during Launch - Seeing Issue using Fabulously Optimized 4.0.0 Beta 

### ISSUE THREAD

**Issue by Chosenbc** [fxmorin/memoryLeakFix#21]
I also use Replay Mod and Voice Chat. I am not going to pretend I know much about this subject at all. But I kept having the crash just as the MC Window itself would open.
Background:
I use MultiMC 5 v0.6.16-3431 as my launcher.
I installed Fabulously+Optimized+4.0.0-beta
Then installed "replaymod-1.19-2.6.5-5-g814d0b7" and "voicechat-fabric-1.19-2.2.45"
I made sure the "sodium-fabric-mc1.19-0.4.2+replaymod.rev.bfbc6de" was installed for Replay Mod.
If Replay Mod is enabled the game Crashes with MemoryLeakFix enabled
If MemoryLeakFix is Disabled there is no issue with crashing.

Does this mean it is MemoryLeakFix, not exactly, I did however try the previous version of Replay Mod "replaymod-1.19-2.6.5-2-g9ce25f7"  which was reported to work before and I have the same issue.

This is highly likely Replay Mod causing the issue, but figured it would be at least somewhat helpful to post this and the Log from the launch when Replay Mod is enabled and so is MemoryLeakFix.

I do plan on doing the same in the Support Discord for ReplayMod.
[FabulouslyOptimized_Replay_VoiceChat_LOG.txt](https://github.com/fxmorin/MemoryLeakFix/files/8924180/FabulouslyOptimized_Replay_VoiceChat_LOG.txt)

**Comment by FxMorin** [comment]
This seems to be an issue with Replay mod, could you please make an issue there

**Comment by Chosenbc** [comment]
I worked with them, this issue appears to be mlf loading "mixins.compat.shaders.replaymod.json:MixinShaderRenderChunk" before this is even called for.

**Comment by FxMorin** [comment]
Yes, they need to properly deal with that. This mod crashes with mods that do hacky work arounds or hacky mixins.
