### ISSUE TITLE
Crash on server load

### ISSUE THREAD

**Issue by ghost** [fxmorin/memoryLeakFix#22]
Hello, I got this error: https://pastebin.com/raw/5zCFVHbx

My mods:
- Fabric API
- Carpet
- Essential Addons (Carpet Extension)
- squaremap

When I try to install squaremap I get this bug, If I disable memoryleakfix it doesn't show up anymore.
Greetings.

EDIT: It is maybe more Essential Addons related and I ask the author about this as well.

**Comment by FxMorin** [comment]
This is an issue with `essentialaddons` @senseiwells stop writing bad code xD
It's probably loading a development mixin or a mixin that is not meant to load normally

**Comment by senseiwells** [comment]
This one has been fixed (https://github.com/Super-Santa/EssentialAddons/issues/45)

**Comment by ghost** [comment]
Awesome:)
