### ISSUE TITLE
Memory Still Leaked when using Mods (ScreenShot)

### ISSUE THREAD

**Issue by ardissaps** [fxmorin/memoryLeakFix#23]
![leak](https://user-images.githubusercontent.com/82106625/174779973-fbde291a-0f16-42c8-8ef4-7962bd5bce78.jpg)

**Comment by FxMorin** [comment]
This mod does not fix all memory leaks, plus Minecraft uses large amounts of memory.
I'm slowly working on fixing more memory leaks
