### ISSUE TITLE
[Incompatibility*] with mod Visual Overhaul

### ISSUE THREAD

**Issue by danieljross** [fxmorin/memoryLeakFix#25]
Minecraft 1.19
Quilt Loader 0.17.1 (beta 6)

mod memoryLeakFix incompatible* with mod [Visual Overhaul](https://github.com/TeamMidnightDust/VisualOverhaul).

\* These mods work together as expected in singleplayer. In a multiplayer scenario (specifically, a LAN environment in which both systems are on the same network running the same game version, modloader and version, and mods (and mod versions)), the player connects to the host machine is kicked immediately after joining. In-game message: "Connection Lost: Disconnected".

The Log does not contain any relevant information since there are no errors raised when this occurs.

Playing on LAN with one or the other of these mods enabled has no issues.

I'm tech literate but not tech educated; I couldn't reasonably deduce which mod was more or less guilty of the issue. Since this mod is more concerned with under-the-hood technical changes, I figured I'd start here. Maybe it has something to do with the fix for Custom Payload packet's buffer leaking? Visual Overhaul is deceivingly _not_ a client-side only mod. Some information is server-side, [based on the mod's description on Curseforge.](https://www.curseforge.com/minecraft/mc-mods/visual-overhaul)

Thanks for your time. I'll do my best to supply additional information if needed.

**Comment by FxMorin** [comment]
Did you test to see if it worked without the Visual Overhaul mod?

**Comment by danieljross** [comment]
> Did you test to see if it worked without the Visual Overhaul mod?

The game behaves as expected when only this mod is installed. I can connect to a LAN server without any issue. Same goes if only Visual Overhaul is installed.

When the mods are installed together, bad behavior cannot he observed in singleplayer. Things work as expected in singleplayer. Bad behavior can only be observed when trying to play multiplayer, if the host server and client are running the same mods.

I should note, when testing this multiplayer problem, things might work correctly at first. It seems like the disconnect only happens if the client’s position in the world is in vicinity of one of the blocks visual overhaul changes (a furnace, jukebox, brewing stand) when that client join the server.
