### ISSUE TITLE
not able to use multiplayer functionality with essential mod

### ISSUE THREAD

**Issue by warior456** [fxmorin/memoryLeakFix#26]
(according to essential dev's)
the issue i have when trying to join a friend singleplayer world is caused by this mod
modpack: https://www.curseforge.com/minecraft/modpacks/tsm18

log of my friend (i lost my log will add it when i can get someone to retry)
[latest (3).log](https://github.com/fxmorin/MemoryLeakFix/files/9128649/latest.3.log)

1.18.2 fabric
edit: it seems like there is a fix for the 1.19 version that might fix this any news on a backport?

**Comment by FxMorin** [comment]
Oh, ya I guess ill make a backport for 1.18.2 for you

**Comment by FxMorin** [comment]
https://github.com/fxmorin/MemoryLeakFix/releases/tag/v0.5.1-1.18
