### ISSUE TITLE
Incompatible with Quilt / Quilted Fabric API

### ISSUE THREAD

**Issue by stantios** [fxmorin/memoryLeakFix#29]
Hello, my game keeps crashing when I tried to join a server. The only mods I have installed are Quilted Fabric API and MemoryLeakFix

Here is the log: https://mclo.gs/Ub85c8R

**Comment by FxMorin** [comment]
Thanks for reporting it, it's a bit weird since it's complaining about something that's impossible. Although ill try to see if I can fix it

**Comment by FxMorin** [comment]
Can you try this version and tell me if it fixes the issue:
https://github.com/fxmorin/MemoryLeakFix/suites/7429800649/artifacts/303492798

**Comment by stantios** [comment]
Nope, it didn't fix. Here is the log: https://mclo.gs/j07kygy

**Comment by FxMorin** [comment]
hmm alright ill continue checking

**Comment by FxMorin** [comment]
Can you check if this fixes the issue:
https://github.com/fxmorin/MemoryLeakFix/suites/7430106336/artifacts/303511842

**Comment by stantios** [comment]
Didn't even get to launch, here is the log: https://mclo.gs/djdMaOz

**Comment by FxMorin** [comment]
We will get there eventually:
https://github.com/fxmorin/MemoryLeakFix/suites/7430587252/artifacts/303544626

**Comment by ChristopherHaws** [comment]
> We will get there eventually: https://github.com/fxmorin/MemoryLeakFix/suites/7430587252/artifacts/303544626

I can confirm that this does fix the issue for me! :)

**Comment by FxMorin** [comment]
Alright then

**Comment by stantios** [comment]
This issue can be closed as this has now been resolved.
