### ISSUE TITLE
More Info

### ISSUE THREAD

**Issue by Julienraptor01** [fxmorin/memoryLeakFix#3]
What special leaks does this mod fixes and how probable am i to encounter one of the leak this mod fixes.
This should be neat to add in description or in a short wiki.

**Comment by Funtimes909** [comment]
Yes please I also would greatly like this

**Comment by fxmorin** [comment]
There you go: https://github.com/fxmorin/memoryLeakFix/wiki/Current-Fixes

**Comment by Madis0** [comment]
What does the second one mean? 
Isn't Sponge a server platform in itself? How would that interact with this mod?

**Comment by FxMorin** [comment]
lol no. SpongePowered is what's used for mixins. Mixins being used in most mods to inject code into the game

**Comment by Madis0** [comment]
Ah, got it.
