### ISSUE TITLE
Crash on server start, possible incompatibility with Dawn API?

### ISSUE THREAD

**Issue by Tempest-5ky** [fxmorin/memoryLeakFix#31]
Basically what the title says! Running a large modpack, memoryleakfix crashes both server and client with a similar error that mentions a mixin failure with DawnAPI.

Mod version is the latest release for 1.18.2

Logs:
https://mclo.gs/ejK8psP
https://crashy.net/jc0ZwhGNLdH0WlJCqcfG

**Comment by FxMorin** [comment]
This needs to be fixed by Dawn API. Please report it there

**Comment by Tempest-5ky** [comment]
Will do, thanks!

Update: It has been fixed on their end in v3.3.2
