### ISSUE TITLE
Crash with "Show Me Your Skin!"

### ISSUE THREAD

**Issue by SplendidAlakey** [fxmorin/memoryLeakFix#35]
**MC** 1.19.1
**Fabric API** 0.58.5
**[Show Me Your Skin!](https://modrinth.com/mod/show-me-your-skin)** 1.2.1
**MemoryLeakFix** 

Logs: https://gist.github.com/Footage2-Amply-Pounce/ab38219c8784e97d7f71c74b057b0295

**Comment by FxMorin** [comment]
This needs to be fixed by ShowMeYourSkin

**Comment by SplendidAlakey** [comment]
Fixed.
