### ISSUE TITLE
Exit Code 1 using 0.5.1 or higher in Minecraft 1.18.1

### ISSUE THREAD

**Issue by EmmettJayhart** [fxmorin/memoryLeakFix#40]
I isolated this mod (0.7.0) from my modpack (1.18.1) to load all on its own, and it still crashes with:

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method freeByteBuffer(Ljava/io/File;IIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in memoryleakfix.mixins.json:hugeScreenshotLeak.MinecraftClient_screenshotMixin from mod memoryleakfix failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap memoryleakfix-refmap.json`

Here is the full log file

[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/9276412/latest.log)

**Comment by EmmettJayhart** [comment]
This is probably related to #38, but #39 that mentioned it doesn't appear to be the same situation.

**Comment by EmmettJayhart** [comment]
I have managed to check the different versions available on the curseforge launcher, and found that the latest version that works is 0.3.5, while all version above and including 0.5.1 will crash.

Looking at the 0.5.1 log file shows the same problem as in 0.7.0
[0.5.1.log](https://github.com/fxmorin/MemoryLeakFix/files/9276443/0.5.1.log)

**Comment by FxMorin** [comment]
Yes its only for 1.18.2
I'll change that so nobody else gets confused
