### ISSUE TITLE
Add support for Minecraft 1.19.2

### ISSUE THREAD

**Issue by rayzchen** [fxmorin/memoryLeakFix#41]

**Comment by FxMorin** [comment]
It already supports 1.19.2, just use the latest jar. Even if it says 1.19.1

**Comment by rayzchen** [comment]
Fabric gives me incompatibility issues

**Comment by rayzchen** [comment]
```
[14:00:36] [main/ERROR]: Incompatible mod set!
 net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
 A potential solution has been determined:
      - Replace mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 with any version that is compatible with:
          - minecraft 1.19.2
 Unmet dependency listing:
      - Mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 requires version 1.19 of 'Minecraft' (minecraft), but only the
     at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
     at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
     at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
     at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
```

Please reopen

**Comment by FxMorin** [comment]
ehh alright I guess ill check why

**Comment by Wide-Cat** [comment]
You are using version 1.19-0.7.0 of the mod. Instead, you need to use 1.19.1-0.7.0 for 1.19.2. You can download it [here](https://cdn.modrinth.com/data/NRjRiSSD/versions/v0.7.0/memoryleakfix-1.19.1-0.7.0.jar)

**Comment by rayzchen** [comment]
Ah, I must have missed that version while looking in the downloads. Thank you!

**Comment by PweSol** [comment]
The curseforge main page and github releases only show the 1.19 version. We have to look into more files on curseforge in order to find it. I think this should be changed that 1.19.2 compatible version is easily visible and accessible. Since most people are on the latest version, and when they download the version presented to them (1.19), it doesn't work.
