### ISSUE TITLE
do "v0.7.0 for 1.19" compatible with 1.19.2

### ISSUE THREAD

**Issue by NalCol** [fxmorin/memoryLeakFix#42]
Quilt Loader will crash and it will say this mod is dependent on 1.19.
if this is a wrong behavour or it will only works on 1.19?

**Comment by rayzchen** [comment]
same as #41

**Comment by NalCol** [comment]
> same as #41

Thanks! Then it is a bug haha

**Comment by rayzchen** [comment]
maybe check #41
