### ISSUE TITLE
3-way incompatibility between Earth2Java, Harvest Scythes, and Memory Leak Fix

### ISSUE THREAD

**Issue by floral-qua-floral** [fxmorin/memoryLeakFix#43]
Version information:
Minecraft 1.19
Fabric loader 0.14.9
[Earth2Java](https://modrinth.com/mod/earth2java) 1.9.0
[Harvest Scythes](https://modrinth.com/mod/harvest-scythes) 2.5.3
[Memory Leak Fix](https://modrinth.com/mod/memoryleakfix) 0.7.0
Fabric API 0.58.0
Architectury 5.12.44 (dependency for Earth2Java)
[Cloth Config](https://modrinth.com/mod/cloth-config) 8.0.75 (unmarked dependency for Earth2Java; see [Issue #89](https://github.com/Slexom/earth2java/issues/89))

The game will fail to launch when all three mods mentioned in the issue title are present. Removing any individual mod resolves the issue. No crash report is generated, however the log file says it's a `java.lang.ExceptionInInitializerError` crash. The full log file is available [here.](https://mclo.gs/GR67zjo) Earth2Java's two dependencies do not have to be removed, so the issue does not lie with Architectury or Cloth Config.

I have reported the issue on all three repos. The three issue reports are at [Slexom/earth2java#90](https://github.com/Slexom/earth2java/issues/90), [LordDeatHunter/HarvestScythes#41](https://github.com/LordDeatHunter/HarvestScythes/issues/41) and [fxmorin/MemoryLeakFix#43](https://github.com/fxmorin/MemoryLeakFix/issues/43).

**Comment by FxMorin** [comment]
Honestly im blaming the other mods on this one. It's a registry issue, so not related to memory leak fix.
My mod loads all mixins at the start of the game instead of when that class is loaded. Which means all issues that would happen normally happen at the start.
