### ISSUE TITLE
MemoryLeakFix + BedrockWaters + Iris + Sodium: crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [fxmorin/memoryLeakFix#46]
**MC** 1.19.2
**FAPI** 0.61.0
**[BedrockWaters](https://www.curseforge.com/minecraft/mc-mods/bedrockwaters)** 1.7.0
**MemoryLeakFix** 0.7.0
**[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)** 0.4.4
**[Iris](https://www.curseforge.com/minecraft/mc-mods/irisshaders)** 1.3.1

To reproduce simply install all 4 mods and run the game.

I suspect the issue is on your side, but I also reported the issue to BedrockWaters just in case.

Logs: https://gist.github.com/Footage2-Amply-Pounce/3051de600d0a701428aa60728e3d7409

**Comment by FxMorin** [comment]
Did you try without memory leak fix?

I suspect this is an issue with the loading order, although I'm not sure and don't have the time to check.

**Comment by FxMorin** [comment]
Ehh seems memory leak fix is not the issue since memory leak fix is not needed for the crash
https://github.com/2Retr0/BedrockWaters/issues/22

**Comment by SplendidAlakey** [comment]
Yes, I tried without it and it is needed for the startup crash, but yeah the mod will crash anyway upon entering a world.

I'll let you know if the dev solves the Iris crash and MemoryLeakFix one still persists.

**Comment by FxMorin** [comment]
Yes memory leak fix simply loads all mixins when the game starts, so any crash that would happen would happen at startup. So its not an issue with memory leak fix
