### ISSUE TITLE
Wrong version on modrinth for 1.19.2

### ISSUE THREAD

**Issue by Aces-and-Jacks** [fxmorin/memoryLeakFix#47]
https://mclo.gs/VeQsjsg

**Comment by Aces-and-Jacks** [comment]
My launcher says it's the wrong version but that's the one that was released on modrinth and it says version 1.19.2 for that release

**Comment by Aces-and-Jacks** [comment]
Ok so I switched to the 1.19.1 version and it worked but would you be able to fix that tag issue?

**Comment by StinkyVoet** [comment]
Same issue on CurseForge. The mod expects version 1.19 specifically instead of 1.19.x
