### ISSUE TITLE
MemoryLeakFix on 1.18.2 causes a crash when running server-side

### ISSUE THREAD

**Issue by NatSquared** [fxmorin/memoryLeakFix#50]
MemoryLeakFix attempts to access net/minecraft/class_746 (ClientPlayerEntity) on the server side, which does not exist because it is a dedicated server. This causes a crash on startup.

Logs: 
[crash-2022-10-01_16.40.04-server.txt](https://github.com/fxmorin/MemoryLeakFix/files/9691388/crash-2022-10-01_16.40.04-server.txt)

**Comment by FxMorin** [comment]
This is not caused by MemoryLeakFix. It's caused by another mod, although memory leak fix loads all mods when the game starts. So another mod caused this
