### ISSUE TITLE
Critical Injection Failure ver 0.7.0

### ISSUE THREAD

**Issue by Thezapman1** [fxmorin/memoryLeakFix#51]
Hello,

The mod crashes when running the latest version of Quilt 0.17.5-beta.3-1.19.2 on Minecraft 1.19.2 with the only other mod qfapi-4.0.0-beta.13_qsl-3.0.0-beta.16_fapi-0.62.0_mc-1.19.2

Changing to the regular fabric api doesn't change anything, and the only modifications I made to the build was changing the fabric api json to include ">=" for the minecraft version because you left it as =1.19 only :|. But even if I swap down a version to 0.5.4 still yields the same injection error.

Logs Below 1 with mods and one without

[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/9694515/latest.log)

[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/9694522/latest.log)

**Comment by Phoenix-Starlight** [comment]
1.19.2 is not compatible with 1.19, just to point out.

**Comment by Thezapman1** [comment]
Yeah I didn't see that there was a 1.19.1 version, my b, that one works
