### ISSUE TITLE
1.19 version of the mod is listed as 1.19.2

### ISSUE THREAD

**Issue by TBV305** [fxmorin/memoryLeakFix#52]
1.19 version of the mod is listed as latest 1.19.2 which causes everyone to think theyre updating/downloading latest version and getting an error that its incompatible 

<img width="725" alt="image" src="https://user-images.githubusercontent.com/72977924/193631679-e3b150da-d32a-4180-b8c6-69a32b498c1e.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/72977924/193632210-fdc2421e-5a52-4ddb-8664-ea6959fdba51.png">

(i didnt know where to say this so i put it here)

**Comment by FxMorin** [comment]
Fixed
