### ISSUE TITLE
Not compatible with 1.19.2

### ISSUE THREAD

**Issue by notIkibo** [fxmorin/memoryLeakFix#54]
[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/9813613/latest.log)

**Comment by Scarlaid** [comment]
I think it does
https://modrinth.com/mod/memoryleakfix/version/v0.7.0-1.19
![image](https://user-images.githubusercontent.com/90851437/197270587-23a4b26c-18bc-4659-b45e-c3d40ec361cb.png)

**Comment by Scarlaid** [comment]
Oops wrong link - https://cdn.modrinth.com/data/NRjRiSSD/versions/v0.7.0/memoryleakfix-1.19.1-0.7.0.jar

**Comment by notIkibo** [comment]
That's epic though I need it on curseforge for my modpack :(
Are you gonna update it there? 👉👈

**Comment by FxMorin** [comment]
Same as #55, nothing I can do about it

**Comment by notIkibo** [comment]
Can't you delete 1.19.1 and reupload it on curseforge? I see that 1.19 was uploaded 2 days later than 1.19.1 and is higher on the list due to that

**Comment by notIkibo** [comment]
![image](https://user-images.githubusercontent.com/106886638/201465348-4ed30356-1f10-4207-8e52-fbae27c51291.png)
![image](https://user-images.githubusercontent.com/106886638/201465351-87cd1e44-0f08-4612-9899-391cbf49ace6.png
It's really just the dates. Sure, the wrong information is that curseforge thinks the newest version is for 1.19.2, but isn't this an easy fix for you to just upload the 1.19.2 again with nothing changed except accepting curseforge's mistakes?
