### ISSUE TITLE
fabric 1.19.2 weird files = crash

### ISSUE THREAD

**Issue by szunakabeats** [fxmorin/memoryLeakFix#55]
the newest upload of your mod is making the game crash. and for some reason it is meant for a older version of mc, but is the newest upload...

![Screenshot 2022-10-23 224845](https://user-images.githubusercontent.com/88375166/197417544-3a99b489-3fbd-466d-8d6b-0cbd6a7c5ef8.png)

**Comment by FxMorin** [comment]
Curseforge launcher is not showing the correct information. The website does, not my problem report it to the launcher
