### ISSUE TITLE
MemoryLeakFix Boot Crash

### ISSUE THREAD

**Issue by SylisMC** [fxmorin/memoryLeakFix#56]
- memoryleakfix-1.19-0.7.0.jar (8/2/2022) Crashes 1.19.2. but is listed on curse forge as intended for 1.19.2
- memoryleakfix-1.19.1-0.7.0.jar (7/30/2022) Works, but is listed as an outdated version because of the previously mentioned issue
- Curseforge installed the wrong version by default for 1.19.2 because of the first mentioned issue

could you remove the 1.19.2 tag on curseforge from memoryleakfix-1.19-0.7.0.jar
And would you also consider re-releasing memoryleakfix-1.19.1-0.7.0.jar as 1.19.X or 1.19.2 in the jar file? its really confusing trying to communicate issues because the jar files name, doesn't match the listed file name, or the intended game version

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/10047634/latest.log)

**Comment by notIkibo** [comment]
I would really love that :)

**Comment by FxMorin** [comment]
Should be fixed in the latest release

**Comment by notIkibo** [comment]
Thank you and ig Im sorry if I were too pushy about my request, but this is good news. Your performance mod brings wonders
