### ISSUE TITLE
Remove 1.19.1 and 1.19.2 from the v0.7.0-1.19.3 release on modrinth

### ISSUE THREAD

**Issue by ChristopherHaws** [fxmorin/memoryLeakFix#60]
https://modrinth.com/mod/memoryleakfix/version/v0.7.0-1.19.3

This release incorrectly is set as compatible with 1.19.1 and 1.19.2. The correct version for those versions of MC is:
https://modrinth.com/mod/memoryleakfix/version/v0.7.0

PrismLauncher keeps updating the file to the wrong version since `v0.7.0-1.19.3` is greater than `v0.7.0` in semver.

**Comment by FxMorin** [comment]
oh thanks
