### ISSUE TITLE
 Minecraft 1.19.3 crash with Simple Voice Chat 2.3.21

### ISSUE THREAD

**Issue by YukiAyase** [fxmorin/memoryLeakFix#61]
I've been testing out the mods I have since yesterday and have narrowed down the mods that was crashing my instance
I installed a fresh instance of **Minecraft 1.19.3** to test it out and make sure that it was the right mod combination that was crashing the instance

Steps to reproduce:
1.) Have MemoryLeakFix and Simple Voice Chat + dependencies installed
2.) Run the game

Without MemoryLeakFix the game runs fine
I also tested it out for **Minecraft 1.19.2** and it runs fine with the latest MemoryLeakFix and Simple Voice Chat

Mods currently installed
cloth-config-9.0.94-fabric
Crafty-Crashes-1.0
fabric-api-0.68.1 1.19.3
lazydfu-0.1.3
memoryleakfix-1.19.3-0.7.0
modmenu-5.0.1
voicechat-fabric-1.19.3-2.3.21

Log file
https://mclo.gs/VU5pAu7

**Comment by mjwells2002** [comment]
This is not a memory leak fix issue, this is a voicechat issue please see https://github.com/henkelmax/simple-voice-chat/issues/503
