### ISSUE TITLE
"Not Responding" message appears every ~5 seconds

### ISSUE THREAD

**Issue by DWW256** [fxmorin/memoryLeakFix#63]
Whenever I start Minecraft with this mod installed, the game throws a "Minecraft is not responding" message every 5 seconds or so.  Obviously this is a huge problem for usability.

I am using all the other mods in the Simply Optimized modpack: https://modrinth.com/modpack/

MemoryLeakFix 0.7.0
Fabric 0.14.11
Minecraft 1.19.3
LWJGL 3.3.1
Prism Launcher 5.1
openSUSE Tumbleweed 20221211
Linux 6.0.10
GNOME 43.1
CPU: AMD Ryzen 5 2500U
GPU: Integrated AMD Radeon Vega 8

**Comment by FxMorin** [comment]
I get this issue running minecraft on linux without any mods...

**Comment by DWW256** [comment]
Really!  Well I did try it with the mod turned off, and that got rid of the issue…I'm finding that it's still generates one or two "Not Responding" messages without the mod, but then they stop.

**Comment by DWW256** [comment]
Whoops, didn't mean to close that.

**Comment by FxMorin** [comment]
Ehh how often does it pop up?

**Comment by FxMorin** [comment]
It doesn't happen to me, and my mod literally does not have the ability to do this. Hence why im confused

**Comment by DWW256** [comment]
Okay, well it's only sporadically happening to me now anyway.  I'll chalk it up to JVM issues or some such (I was using OpenJ9) and close the issue.
