### ISSUE TITLE
Version's MC version incorrectly marked

### ISSUE THREAD

**Issue by srnyx** [fxmorin/memoryLeakFix#64]
Assuming that https://modrinth.com/mod/memoryleakfix/version/v0.7.0-1.19 is for 1.19, 1.19.1, **and** 1.19.2, the MC version is incorrectly marked on Modrinth and in the JAR file.
On modrinth and in the JAR file (`fabric.mod.json`), it has it's compatible MC version set to `1.19`, however, I assume it should be `1.19-1.19.2` on Modrinth and `>=1.19` (or `1.19.x`) in `fabric.mod.json`.
If it is incorrect, please release an update to fix it as it's breaking my modpack, thank you!

**Comment by FxMorin** [comment]
No that version only works on 1.19, there is another version for 1.19.1-1.19.2

**Comment by srnyx** [comment]
> No that version only works on 1.19, there is another version for 1.19.1-1.19.2

Oh, I see it now, my bad. In the future, could the versions that support later MC versions be released after ones that support earlier MC versions? This way when using [packwiz](https://github.com/packwiz/packwiz) (and having 1.19-1.19.2 as compatible MC mod versions [cause some mods love to not update even though they support later versions]) it'll use the correct mod version.
