### ISSUE TITLE
Porting to Forge

### ISSUE THREAD

**Issue by SrRapero720** [fxmorin/memoryLeakFix#66]
Searching about i dont found any port to forge, so i want to make a port. can i?
(i ask because)
https://github.com/fxmorin/MemoryLeakFix/blob/25e6c9df056e732a91a4340450cc62a829708d6c/README.md?plain=1#L27

**Comment by FxMorin** [comment]
Unfortunately no.
As forge already fixes a few of them and the mixins would have to be completely different
