### ISSUE TITLE
Conflict with Universal Graves Mod

### ISSUE THREAD

**Issue by nimids** [fxmorin/memoryLeakFix#67]
When enter a single person world I get "disconnected" with this error:
![image](https://user-images.githubusercontent.com/80544703/210464663-08b17fc7-cbb0-4c8c-b7ba-babfcdd86310.png)

Here's the log:
[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/10340710/latest.log)

**Comment by FxMorin** [comment]
Are you sure this is caused by Universal Graves?

**Comment by nimids** [comment]
Before posting the conflict was verified and the log was produced by starting with an empty .minecraft folder.
First started Minecraft 1.19.3.
Then installed FabricLoader 0.14.12 with the fabric installer.
And added the following mods:
- fabric-api 0.71.0+1.19.3
- memoryleakfix 1.19.3-0.7.0
- universal-graves 2.2.0+1.19.3

Then starting a new world produces the crash/disconnect.
Removing memoryleakfix or universal-graves and starting a new world works.

**Comment by FxMorin** [comment]
Interesting, can you report this on universal graves also

**Comment by nimids** [comment]
Issue fixed by updating Polymer library.
