### ISSUE TITLE
Version 0.7.0 isn't recognized as compatible with 1.19.2 by Fabric despite saying it is on Curseforge

### ISSUE THREAD

**Issue by Qhn-bncyqy** [fxmorin/memoryLeakFix#68]
It says it needs version 1.19, but Curseforge says 1.19-1.19.2, and there is no other version for 1.19.2
![image](https://user-images.githubusercontent.com/45434552/213955817-f8ed90a4-7ad3-4562-bdf8-eea36822b007.png)

**Comment by FxMorin** [comment]
Curseforge website or curseforge launcher, cause the launcher has proven to be garbage
