### ISSUE TITLE
Crash on startup with essential.gg

### ISSUE THREAD

**Issue by craftish37** [fxmorin/memoryLeakFix#7]
As mentionned in #5 , some people have issues different from the one the original reporter got

Here's mine, using latest Quilt version (0.17.1-beta) in 1.18.2
[latest.log](https://github.com/fxmorin/memoryLeakFix/files/8808673/latest.log)

Don't feel bad to ask me anything, it's always a pleasure to see such mods with quick answers like I saw hours ago :D

**Comment by FxMorin** [comment]
@altrisi This one is even better. Not only does the force loading silencer not work. I think we got the SdpFactory cause: `gg.essential.lib.ice4j.ice.sdp.IceSdpUtils`
Alright ill have to look at it later although can you try removing essential... oh that's a loader.

Would it be possible for you to try running the mods in a non-essential launcher and without essential to see if that fixes the issue. Thanks

**Comment by craftish37** [comment]
Of course I can, lemme a minute and I’ll provide results 😁
Also thanks for the answer 👀

**Comment by craftish37** [comment]
Works, sounds like a Quilt or Essentials incompatibility
Note : removed fake floader and updated debugify since last test

**Comment by craftish37** [comment]
Tested with and without all the suspicious mods, defintely an Essential conflict

**Comment by FxMorin** [comment]
Alright, we are getting somewhere. I have time to look at it now, so ill get on that

**Comment by craftish37** [comment]
K, I'm not sure if my (very) limited knowledge will help, but if you need anything, just ask 😉

**Comment by FxMorin** [comment]
Is essential just cosmetics that you pay for?
Oh even better, it seems to be closed source

**Comment by craftish37** [comment]
I don't use it for the cosmetics, I'm working with the cosmetica team 👀
Essential is closed source, but I'm pretty sure they will give you infos on discord 👌

**Comment by FxMorin** [comment]
lol what do you use it for then?

**Comment by craftish37** [comment]
IG private chat, open a solo world to mates, friendlist system and much more that I'm lazy enough to put in a open-source mod 🤣

**Comment by fxmorin** [comment]
They keep saying mod, although it's basically impossible to get the mod. You are forced to get the installer, sounds like a decently simple mod that's making itself look good. I was just about to say, its probably not hard to just get open-source versions

**Comment by fxmorin** [comment]
Oh sk1ers a dev, yup it's the opposite communities I stay away from.  Oboi alright let's hack fix this

**Comment by FxMorin** [comment]
Mind sending a crash log to them as well, since tbh I don't think I can do much about them not following protocol setup by fabric, and quilt

**Comment by FxMorin** [comment]
Log spamming issue has just been fixed, should be out in the next build

**Comment by FxMorin** [comment]
Awaiting response from essential.gg

**Comment by FxMorin** [comment]
Temporarily fixed in v0.4.1 until essential fixes it themselves
