### ISSUE TITLE
Crash with Sodium 0.4.9

### ISSUE THREAD

**Issue by HhiPyrene** [fxmorin/memoryLeakFix#72]
[crash-2023-02-07_14.21.59.7670-quilt_loader.txt](https://github.com/fxmorin/MemoryLeakFix/files/10673401/crash-2023-02-07_14.21.59.7670-quilt_loader.txt)
[latest.log](https://github.com/fxmorin/MemoryLeakFix/files/10673402/latest.log)

**Comment by FxMorin** [comment]
This is not a bug with sodium. It's a crash caused by `cullleaves`
