### ISSUE TITLE
Wiki not fully updated after 0.8.0

### ISSUE THREAD

**Issue by TheBossMagnus** [fxmorin/memoryLeakFix#76]
![Screenshot_20230309-062202.png](https://user-images.githubusercontent.com/92474350/223927956-bb906dfc-fff1-439e-b70f-611bcbe48db0.png)
It still say six fixes as 0.7.0 instead of 7 as 0.8.0
https://github.com/fxmorin/memoryLeakFix/wiki/Current-Fixes

**Comment by FxMorin** [comment]
thanks for telling me

**Comment by FxMorin** [comment]
I've made the wiki public. So in the future you can just modify it yourself ;)
