### ISSUE TITLE
Ticking entities crashing game

### ISSUE THREAD

**Issue by Shoes4Clues** [fxmorin/memoryLeakFix#83]
Latest version for 1.18.2 Fabric. Crash logs are attached.
[crash-2023-03-15_06.54.31-server.txt](https://github.com/fxmorin/MemoryLeakFix/files/10980762/crash-2023-03-15_06.54.31-server.txt)

**Comment by Kamiszewskyy** [comment]
Can confirm the crash above. I got it multiple times.

**Comment by wendavid552** [comment]
It seems to be duplicate of #82 .

**Comment by mulukou** [comment]
can confirm, also crashing for me on the latest version, moving it back to 0.7.0 seems to fix the issue

**Comment by FxMorin** [comment]
This has been fixed internally and will be in the next release

**Comment by FxMorin** [comment]
Duplicate of #82
