### ISSUE TITLE
1.18.2 Crash on startup

### ISSUE THREAD

**Issue by border999** [fxmorin/memoryLeakFix#89]
[the issue.txt](https://github.com/fxmorin/MemoryLeakFix/files/11069497/the.issue.txt)

**Comment by contariaa** [comment]
fixed in <https://github.com/fxmorin/MemoryLeakFix/pull/88/commits/9a08217d08bdb6ce42f491fb32496df5cafe3553>

**Comment by 5stigma** [comment]
same problem
