### ISSUE TITLE
Crash on startup with Dawn API

### ISSUE THREAD

**Issue by SplendidAlakey** [fxmorin/memoryLeakFix#9]
**MC** 1.18.2
**Fabric API** 0.54.0
**[Dawn API](https://www.curseforge.com/minecraft/mc-mods/dawn/files/3805531)** 3.3.1
**memoryLeakFix** 0.3.3

Logs: https://gist.github.com/Footage2-Amply-Pounce/2b50a36ef00ad25a63ff2b0cfcfc8994

**Comment by FxMorin** [comment]
@altrisi Found the issue. It needs to be fixed on Dawn-Api's side. https://github.com/DawnTeamMC/DawnAPI/issues/26

**Comment by SplendidAlakey** [comment]
Fixed on Dawn API side: https://github.com/DawnTeamMC/DawnAPI/commit/37e6df0c7bc6a5b47b5ac00cd92eb3cc77ec53b8
