### ISSUE TITLE
1.19.4 crash on startup with beta 4

### ISSUE THREAD

**Issue by voidrinix** [fxmorin/memoryLeakFix#90]
Crash log: https://mclo.gs/eMiqv9J

**Comment by TechPro424** [comment]
I'm crashing on 1.19.2
https://mclo.gs/U4vPQrS

**Comment by contariaa** [comment]
for reference: https://github.com/fxmorin/MemoryLeakFix/issues/93#issuecomment-1484074585

**Comment by FxMorin** [comment]
Should be fixed in beta 5
