### ISSUE TITLE
Callback method memoryLeakFix$captureByteBuffer from mod memoryleakfix failed injection check

### ISSUE THREAD

**Issue by Madis0** [fxmorin/memoryLeakFix#93]
https://mclo.gs/sSxw0pB
v1.0.0-beta.4 for 1.19.4

This crashed after adding the mod to [Fabulously Optimized's](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files) latest 4.7.0 alpha (7 at the time). Notably MemoryLeakFix also exists on the modpack's 4.6.0 version (Minecraft 1.19.3) and no such crash has occurred.

**Comment by contariaa** [comment]
fixed in https://github.com/fxmorin/MemoryLeakFix/commit/f09c2213db4e79796ff52a3b9ee233d923e4923a, coming in beta 5

**Comment by FxMorin** [comment]
Should be fixed in beta 5

**Comment by Madis0** [comment]
Works.
