### ISSUE TITLE
MemoryLeakFix 1.0.0-beta.4 incorrectly specifies a minimum `java` virtual dependency target of `17` in `fabric.mod.json`, which prevents it from being loaded due to dependency resolution issues on Minecraft <= 1.16.5 (JDK 8) and 1.17.x (JDK 16).

### ISSUE THREAD

**Issue by akemin-dayo** [fxmorin/memoryLeakFix#94]
MemoryLeakFix 1.0.0-beta.4 incorrectly specifies a minimum `java` virtual dependency target of `17` in `fabric.mod.json`, which prevents it from being loaded due to dependency resolution issues on Minecraft <= 1.16.5 (JDK 8) and 1.17.x (JDK 16).

The actual bytecode in the class files themselves are compiled using the correct JDK target (JDK 8, class version 52) — the issue lies _solely_ in `fabric.mod.json` metadata.

**Comment by contariaa** [comment]
fixed in https://github.com/fxmorin/MemoryLeakFix/commit/5c934addfee7d73e572bdc104eaf1a59fd4595f7, coming in beta 5

**Comment by FxMorin** [comment]
Should be fixed in beta 6
